# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43961b0afb6f1f0c0081e3937a60f414efae8822617a9358bc0afb54c16548217514e29094a50746d7c4b85c31a3a9fc2082f03ea005b2bf4b362d2d4f6937fb

test:
  secret_key_base: ecd52eee02bfbd04704e5b53705a08d5a01f948400b7bb5f0bebb02509979b52e51cd4f83c162991e1c8fdcb22ad720da1d2dce3782a3facb0b39a7ad97deea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
